### ISSUE TITLE
Create blogs page

### ISSUE THREAD

**Issue by TazDeCoder** [TazDeCoder/blog-site#1]
### Tasks:
- [ ] Create UI of the page
- [ ] Retrieve blogs from 'blog-api' and render them
- [ ] Links to visit any selected blog post
