### ISSUE TITLE
Create blogs page

### ISSUE THREAD

**Issue by TazDeCoder** [TazDeCoder/blog-site#2]
### Tasks:
- [ ] Create UI of the page
- [ ] Retrieve blogs from Strapi and render them
- [ ] Links to visit any selected blog post
