### ISSUE TITLE
Create category template

### ISSUE THREAD

**Issue by TazDeCoder** [TazDeCoder/blog-site#5]
### Tasks:
- [ ] Create UI of the template
- [ ] Retrieve category from strapi and render its details (i.e. category type)
- [ ] Render articles associated with category
